name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm audit --production
  test:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
